# Project name
spring.application.name=emergency-text-back

# mariadb
# spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mariadb://${RDS_ENDPOINT}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# API
external.api.url=${API_URL}
external.api.key=${API_KEY}

# URL
spring.app.url=${SPRING_APP_URL:http://localhost:8080}